allowBuilds:
  bufferutil: set this to true or false
  esbuild: set this to true or false
  ffmpeg-static: set this to true or false
  ip-set: set this to true or false
  node-datachannel: set this to true or false
  utf-8-validate: set this to true or false
  utp-native: set this to true or false
onlyBuiltDependencies:
  - ffmpeg-static
  - bufferutil
  - utf-8-validate

overrides:
  uint8-util: <2.3.0
